### ISSUE TITLE
`yarn deploy` failing with `the method has been deprecated: eth_accounts` (Ephemery)

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/protocol#617]
I am trying to use the instructions [here](https://github.com/livepeer/protocol/blob/confluence/README.md) to deploy the protocol to the Ethereum Ephemery testnet.

Steps to reproduce:

1. clone the protocol repo with:
```
git clone https://github.com/livepeer/protocol.git
```
2. copy the `.env.sample` file to `.env`
3. add a private key, corresponding to an address with funds on Ephemery, to `PRIVATE_KEY=`
4. Add the following in `hardhat.config.ts` under `networks`:
```
        ethereumEphemeryDevnet: {
            url: `https://otter.bordel.wtf/erigon`,
            accounts: PRIVATE_KEY ? [`0x${PRIVATE_KEY}`] : undefined
        },
```
5. Set the `defaultNetwork` in hardhat.config.ts to `ethereumEphemeryDevnet`.
6. Run the following:
```
yarn
export LPT_DEPLOYMENT_EXPORT_PATH=~/Development/lpt_contracts.json
yarn deploy
```
7. See error:
```
An unexpected error occurred:

ProviderError: the method has been deprecated: eth_accounts
    at HttpProvider.request (/home/ubuntu/protocol/node_modules/hardhat/src/internal/core/providers/http.ts:49:19)
    at GanacheGasMultiplierProvider.request (/home/ubuntu/protocol/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:312:34)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
error Command failed with exit code 1.
```

**Comment by chrishobcroft** [comment]
Closing. It appears to be the case that the RPC endpoint being used did not support this method.
